server:
  port: 8088
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: picture-service
          uri: lb://PICTURE-SERVICE
          predicates:
            - Path=/api/picture/**
        - id: api-app
          uri: lb://API-APP
          predicates:
            - Path=/api/**
        - id: admin-app
          uri: lb://ADMIN-APP
          predicates:
            - Path=/admin/**