version: '3'
services:
  spring-cloud-config:
    image: smart-home/spring-cloud-config:latest
    ports:
      - 8888

  client-app:
    image: smart-home/client-app:latest
    ports:
      - 8080:80
    depends_on:
      - admin-app
      - api-app
      - picture-service

  admin-app:
    image: smart-home/admin-app:latest
    ports:
      - 8080
    volumes:
      - ./storage:/var/storage
    environment:
      - PROFILE=docker
      - CONFIG_SERVER_URL=http://spring-cloud-config:8888
    command: bash -c "/apps/wait-for-service.sh db 3306 && /apps/wait-for-service.sh spring-cloud-config 8888 && /apps/entrypoint.sh"
    depends_on:
      - db
      - redis
      - spring-cloud-config

  api-app:
    image: smart-home/api-app:latest
    ports:
      - 8085:8080
    environment:
      - PROFILE=docker
      - CONFIG_SERVER_URL=http://spring-cloud-config:8888
    command: bash -c "/apps/wait-for-service.sh db 3306 && /apps/wait-for-service.sh spring-cloud-config 8888 && /apps/entrypoint.sh"
    depends_on:
      - db
      - redis
      - spring-cloud-config

  picture-service:
    image: smart-home/picture-service:latest
    ports:
      - 8080
    volumes:
      - ./storage:/var/storage
    environment:
      - PROFILE=docker
      - CONFIG_SERVER_URL=http://spring-cloud-config:8888
    command: bash -c "/apps/wait-for-service.sh db 3306 && /apps/wait-for-service.sh spring-cloud-config 8888 && /apps/entrypoint.sh"
    depends_on:
      - db
      - spring-cloud-config

  db:
    #    image: postgres
    #    restart: always
    #    environment:
    #      POSTGRES_PASSWORD: password
    #    ports:
    #    - 5432:5432

    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  my-db: